<?php ini_set('display_errors', 'Off'); ?>
<!-- Content Section -->
<div class="overlay__wrapper">
    <div class="overlay overlay__browse" data-target="#browseDropdown"></div>
    <section class="content__wrapper">
        <div class="container">
            <br><br><br>
            <h2><strong>MATIXdental End-User Terms of Use</strong></h2>
            <p><em>Last Updated: May 17th, 2017</em></p>
            <div class="row">
                <div class="col-md-12 col-xs-12">
                    <p>These Terms of Use govern the use of and access to MATIXdental. By accessing or using MATIXdental, or by otherwise accepting these Terms of Use, you agree to these Terms of Use. If you violate or do not agree to these Terms of Use, your access to and use of MATIXdental is unauthorized. </p>
                    <p><strong>In these Terms of Use:</strong></p>
                    <ul>
                        <li>When we say &ldquo;MATIXdental&rdquo;, we mean Dentomatix.com,LLC. and any subsidiaries vendor partners, and affiliates of MATIXdental (including any that MATIX may form or acquire in the future). We also refer to MATIXdental as 'we', 'us' and 'our'. </li>
                        <li>When we say &ldquo;MATIXdental Sites&rdquo;, we mean <a href="http://www.jet.com/">www.MATIXdental.com</a>, the MATIXdental.com apps, and all related services, content, functionality, and transactions offered by MATIXdental on or through <a href="http://www.jet.com/">www.MATIXdental.com</a> and the MATIXdental.com apps.</li>
                        <li>When we say &ldquo;you&rdquo; or &ldquo;your&rdquo; we mean users of MATIXdental.</li>
                        <li>When we say &ldquo;Terms of Use&rdquo;, we mean these Terms of Use and all other terms and policies on MATIXdental and any updates to those terms and policies</li>
                        <li>IMPORTANT: BY USING MATIXDENTAL, YOU AGREE TO RESOLVE ANY DISPUTE WITH MATIXDENTAL THROUGH BINDING ARBITRATION, NOT IN COURT, AND YOU WAIVE CERTAIN RIGHTS TO PARTICIPATE IN CLASS ACTIONS. CERTAIN EXCEPTIONS AND WAIVERS ARE DETAILED IN SECTIONS 15 AND 16.</li>
                    </ul>
                    <p>While all of these Terms of Use contain important points, please note the warranty disclaimers and limitations on MATIXdental&rsquo;s liability explained in sections 11 and 12 in particular. As a continuously evolving shopping platform, we must disclaim or limit our liabilities relating to MATIXdental and the products on MATIXdental.</p>
                    <h4><strong>1. Account Registration</strong></h4>
                    <p>To use the services of MATIXdental, you must register for an account <a href="https://jet.com/register?login">here</a>. You must be at least 18 years old to register for an account. You agree that all of your registration information will be true and complete, and you will keep your account information current and up-to-date. You agree to keep your MATIXdental username and password confidential, and to access MATIXdental from devices that have up-to-date operating systems and security software. You agree not to allow anybody else to use your account, including in any way that is meant to circumvent these Terms of Use. You will be responsible for all purchases made, and anything else that occurs, through your account. Please notify us immediately of any suspected unauthorized activity on your account by sending an email to <a href="mailto:admin@MATIXdental.com">admin@MATIXdental.com</a>.</p>
                    <h3><strong>2. Placing an Order on MATIXdental Marketplace or Affiliated Site</strong></h3>
                    <p>In order to purchase FDA restricted products, you must provide the appropriate licensure credentials including your Full Name, License Number (state of issuance/renewal/expiration date) NPI number and applicable DEA number. We also request a valid phone number in order to expedite the verification request and resolve any conflicts. The state of licensure must match the destination of purchased products. MATIXdental will verify your active licensure status, and notify you with a confirmation email prior to activating your account and allowing your first transaction. Prior to authentication, the purchase request will have a &lsquo;pending&rsquo; status, and will be processed immediately upon verification. </p>
                    <h4><strong>Shipping</strong></h4>
                    <p>MATIXdental vendors ship within the contiguous United States (48 states and District of Columbia), Alaska and Hawaii. For more information about shipping and delivery, please see our <a href="https://jet.com/help-center/shipping-and-delivery">Shipping &amp; Delivery policy</a>.</p>
                    <h4><strong>Orders and Pricing</strong></h4>
                    <p>Each product&rsquo;s list price is set by the vendor selling the product. MATIXdental does not set or alter the pricing, promotional ability, taxation or shipping price.</p>
                    <p>As you shop on MATIXdental you must review your entire final order, including your cart savings, total purchase price, and each individual item price, before submitting your final purchase request at checkout.</p>
                    <p>Pricing errors, out-of-stock and other errors occasionally occur on MATIXdental. We reserve the right to cancel any orders containing pricing errors, out of stock errors or other errors at any time without further obligation to you, including after you have received a confirmation of your order.</p>
                    <h4><strong>Taxes</strong></h4>
                    <p>Items sold on MATIXdental may be subject to tax. Prior to submitting your purchase request, you will see an estimate of the tax to be collected on your order. This tax amount will depend on various factors, including the items purchased, the shipment destination, and the identity and location of the seller(s).</p>
                    <p>The seller of items purchased on MATIXdental is directly selected by you the user. Any applicable tax on those items will be applied to the item price you pay for taxable items, less any savings amounts.</p>
                    <p>Items will be subject to tax based on the sales tax collection obligations of the seller. Applicable tax on such orders will be applied to the item price indicated by the seller.</p>
                    <h4><strong>Title and Risk of Loss</strong></h4>
                    <p>Title to the items purchased by you on MATIXdental (and the related risk of loss on these items) passes to you upon delivery of the items to the common carrier used by MATIXdental vendors.</p>
                    <h4><strong>Returns and Refunds</strong></h4>
                    <p>Returns and refunds are available only as described in the <a href="https://jet.com/help-center/shipping-and-returns">Returns/Refund policy</a> of your selected vendor(s). While MATIXdental will facilitate vendor communication to provide returns and refunds, excessive or abusive returns or attempted returns may void our Returns/Refund policy and any guarantees on future orders.</p>
                    <h4><strong>Resale</strong></h4>
                    <p>We reserve the right to prohibit or limit sales to resellers or other parties who purchase a product from MATIXdental with the intention to resell that product. We also reserve the right to limit the quantity of items purchased per account, credit card, shipping address, person, household or order for any reason.</p>
                    <h4><strong>3. Accuracy, Completeness and Timeliness of Information on MATIXdental:</strong></h4>
                    <p>MATIXdental contain information provided by third party sellers and other content providers. Despite our efforts to be accurate, we don't guarantee any aspect of any product information on MATIXdental, including, without limitation, product images, descriptions and specifications. The information on MATIXdental is for information purposes only, and may be inaccurate, incomplete, out-of-date, unreliable, miscategorized, or not helpful. Product information contained on MATIXdental may differ from information contained on the actual product materials. Before you act on information you find on MATIXdental, you must independently confirm any facts about the item(s) that are important to your decision. </p>
                    <p>If you purchase a product that is not as described, your sole remedy against MATIXdental is to return it and/or request a refund in accordance with our <a href="https://jet.com/help-center/shipping-and-returns">Returns/Refund policy</a>.</p>
                    <p>If you find an error on MATIXdental, please let us know by contacting us at <a href="mailto:admin@MATIXdental.com">admin@MATIXdental.com</a> in order to improve that content or aspect in question.</p>
                    <h4><strong>4. Privacy</strong></h4>
                    <p>You consent to the collection, use, disclosure and other handling of information as described in our <a href="https://jet.com/privacy-policy">Privacy Notice</a>, which may occasionally be updated. You consent to our monitoring and recording of telephone calls, emails, and texts (and other forms of communications) between you and us, no matter who initiates the communication.</p>
                    <h4><strong>5.TBD</strong></h4>
                    <h4><strong>6. Use of Materials on MATIXdental</strong></h4>
                    <p>All content on MATIXdental (including, for example, text, designs, graphics, logos, icons, images, audio clips, downloads, interfaces, information, code and software, and the selection and manner of compilation and presentation), is owned by MATIXdental, other content providers (such as MATIXdental&rsquo;s retail partners or suppliers) or their licensors, and may be protected by copyright, trademark, and other applicable laws.</p>
                    <p>Your access to and use of MATIXdental does not grant you any license or right to use any trademark, logo, or service mark displayed on MATIXdental. MATIXdental, other content providers, or their licensors retain full and complete title to and reserve all rights in the material on MATIXdental, including all associated intellectual property rights. MATIXdental neither warrants nor represents that your use of materials on MATIXdental will not infringe rights of third parties.</p>
                    <p>You may access MATIXdental only for your professional use, and you may not modify or delete any copyright, trademark or other proprietary notice relating to the material you access.</p>
                    <p>Any other use of the material on MATIXdental, including, without limitation, the modification, distribution, transmission, performance, publication, uploading, licensing, reverse engineering, transfer, or sale of, or the creation of derivative works from, any material, information, software, products, or services obtained from MATIXdental, or use of MATIXdental for purposes competitive with MATIXdental, or for other commercial purposes, is expressly prohibited. You agree to abide by all additional restrictions displayed on MATIXdental as they may be updated from time to time.</p>
                    <h4><strong>7. Materials You Submit</strong></h4>
                    <p>You acknowledge that you are responsible for all materials you submit to MATIXdental via MATIXdental.com or other electronic communications (including through any part of MATIXdental administered by third parties like Facebook, Instagram, other social media platforms and the tools that allow you to interact with MATIXdental through these social media platforms). This means you are responsible for the legality, accuracy, appropriateness, originality, and copyright of any such material you submit.</p>
                    <p>Unless we indicate otherwise, if you submit any material to us, you grant MATIXdental an unrestricted, worldwide, nonexclusive, royalty-free, perpetual, irrevocable, and fully sublicensable right to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and display these material throughout the world in any media. You further agree that MATIXdental is free to use any ideas, concepts, feedback, and know-how you provide to MATIXdental. You grant MATIXdental the right to use the name you submit in connection with such material if we choose. You represent and warrant that you own or otherwise control in perpetuity all the rights to the content you submit, that such content is accurate, and that use of such content will not violate any law or these Terms of Use.</p>
                    <p>You agree not to submit content that:</p>
                    <ul>
                        <li>infringes or violates anyone else&rsquo;s patent, copyright, trademark, trade secret, rights of publicity or privacy, or other intellectual property rights;</li>
                        <li>is illegal or encourages illegal activities or any breach or violation of a right (including a contractual right) held by a third party;</li>
                        <li>is fraudulent, false, misleading, or deceptive;</li>
                        <li>is defamatory, obscene, pornographic, vulgar, or offensive;</li>
                        <li>promotes discrimination, bigotry, racism, hatred, harassment, or harm against any individual or group;</li>
                        <li>is violent or threatening, or promotes violence against, or actions that are threatening to, any individual or group;</li>
                        <li>has a commercial purpose;</li>
                        <li>is intended to cause harm, damage, disable, or otherwise interfere with MATIXdental or our partners; or</li>
                        <li>can be considered a third party&rsquo;s private or confidential information.</li>
                    </ul>
                    <h4><strong>8. Restrictions on Access and Use</strong></h4>
                    <p>When accessing and using MATIXdental, you agree not to do the following:</p>
                    <ul>
                        <li>Violate any law, rule, regulation, or these Terms of Use;</li>
                        <li>Engage in conduct that is fraudulent or otherwise harmful to MATIXdental, our partners, or any other user;</li>
                        <li>Display to others, mirror, or frame MATIXdental, or any component of MATIXdental;</li>
                        <li>Access MATIXdental if we have prohibited you from such access;</li>
                        <li>Circumvent any rules or terms set forth on MATIXdental including those relating to any promotion, contest or program on MATIXdental;</li>
                    </ul>
                    <p>You will not do any of these things:</p>
                    <ul>
                        <li>Access, tamper with, or use non-public areas of MATIXdental, MATIXdental&rsquo;s computer systems, or the technical delivery systems of MATIXdental or MATIXdental&rsquo;s providers;</li>
                        <li>Probe, scan, or test the vulnerability of any MATIXdental Sites or breach any security or authentication measures;</li>
                        <li>Interfere with the access of any user, host or network, including, without limitation, by sending a virus, overloading, flooding, spamming, or mail-bombing MATIXdental;</li>
                        <li>Avoid, bypass, remove, deactivate, impair, descramble, or otherwise circumvent any technological measure intended to protect, limit access to, or control MATIXdental;</li>
                        <li>Decipher, decompile, disassemble, or reverse engineer any of the software used on or in connection with MATIXdental;</li>
                        <li>Collect any personally identifiable information from users of MATIXdental or use any such information found on MATIXdental;</li>
                        <li>Use a third party&rsquo;s credentials, conceal your true IP address, or otherwise impersonate or misrepresent your identity or affiliation with any person or entity;</li>
                        <li>Use MATIXdental to determine whether a third party holds any type of account, or to learn about or verify information about the account that is not yours;</li>
                    </ul>
                    <p>You will not use MATIXdental Sites or MATIXdental&rsquo;s name, logo, brand or identity to do any of these things:</p>
                    <ul>
                        <li>Send any unsolicited or unauthorized advertising, promotional materials, email, junk mail, spam, chain letters, or other form of solicitation;</li>
                        <li>Use any meta tags or other hidden text or metadata utilizing a MATIXdental trademark, logo, URL, or product name without MATIXdental&rsquo;s express written consent;</li>
                    </ul>
                    <ul>
                        <li>And, you will not attempt to do anything, or permit, encourage, assist, or allow any third party to do anything, prohibited in this list of bulleted items, or attempt, permit, encourage, assist, or allow any other violation of these Terms of Use.</li>
                    </ul>
                    <p>You agree not to, directly or indirectly (e.g., through a third party), attempt to access, search, or otherwise use MATIXdental (such as by attempting to retrieve information from or about MATIXdental) through the use of any engine, software, tool, agent, device, or mechanism (including, without limitation, spiders, robots, crawlers and data mining tools) other than generally available third-party web browsers that (1) provide accurate and complete User-Agent information in the HTTP header, such as Safari, Firefox, Chrome, and Internet Explorer and (2) have not been modified with plugins or otherwise in a manner that facilitates automated or faster-than-normal access to, searching of, or other use of MATIXdental. You also agree not to disregard our robots.txt files (but in the event of a conflict between these Terms of Use and a MATIXdental Site&rsquo;s robots.txt file, the more restrictive of the two shall apply.)</p>
                    <p>If you attempt to access, search, or otherwise use MATIXdental in any way other than through a generally available third-party web browser meeting the conditions described above, or if you disregard our robots.txt files, you agree that such action shall constitute your permanent consent and authorization for MATIXdental to immediately and without notice to you, access, search, retrieve information from or about, or otherwise use, any websites that you or your affiliates own, operate, or control, through any engine, software, tool, agent, device, or mechanism that MATIXdental considers appropriate, including, without limitation, spiders, robots, crawlers and data mining tools, regardless of any statement on such websites (or in their terms of use, terms of service, robots.txt files, or the like) to the contrary, either directly or indirectly (e.g., through a third party).</p>
                    <p>If you are accessing MATIXdental as an employee or agent, you acknowledge that you are extending the permanent consent and authorization described above on behalf of your employer or principal, and you represent that you have authority from that employer or principal to do so.</p>
                    <p>If you are accessing MATIXdental as an employer or principal, you authorize your employee or agent to extend on your behalf the permanent consent and authorization described above, and you acknowledge that your permanent consent and authorization will bind all of your employees and agents.</p>
                    <h4><strong>9. Notice of Copyright Infringement</strong></h4>
                    <p>MATIXdental has reserved the right, in its sole discretion, to terminate the accounts of users of MATIXdental who infringe on copyrights of MATIXdental or others. MATIXdental has designated an agent to receive notices of claimed copyright infringement relating to MATIXdental under the Digital Millennium Copyright Act, 17 U.S.C. &sect; 512(c). If you believe that your copyright, or the copyright of a person on whose behalf you are authorized to act, has been infringed, you must send a written notice to MATIXdental containing the following information:</p>
                    <ul>
                        <li>A physical or electronic signature of the owner of, or a person authorized to act on behalf of the owner of, an exclusive right that is allegedly infringed.</li>
                        <li>Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works are covered by a single notification, a representative list of such works.</li>
                        <li>Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit us to locate the material.</li>
                        <li>Contact information for the notifying party, including name, address, telephone number, and email address.</li>
                        <li>A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law.</li>
                        <li>A statement that the information in the notification is accurate, and under penalty of perjury, that you are the owner of, or authorized to act on behalf of the owner of, an exclusive right that is allegedly infringed.</li>
                    </ul>
                    <p>You must submit your written notice containing the above information by fax, email, or postal to the following Designated Agent:</p>
                    <p>MATIXdental.com Copyright Agent 700 S Flower Street Suite 2990, Los Angeles, CA 90017 Email: admin@MATIXdental.com</p>
                    <h4><strong>10. Communications Decency Act Notice</strong></h4>
                    <p>Commercially available parental control protections (such as computer hardware, software, or filtering services) may assist you in limiting access to material on the Internet that is harmful to minors. Current providers of such protections include McAfee and Symantec, as well as others available from <a href="https://www.google.com/search?q=parental+control+software&amp;gws_rd=ssl%20target=">this Google search</a>. Please note that we did not create these parental control tools, and we have not tested or evaluated them. Your use of these tools on MATIXdental is at your sole risk. You should not assume that these or any other third-party parental control protections will work on MATIXdental.</p>
                    <h4><strong>11. DISCLAIMER OF WARRANTIES</strong></h4>
                    <p>This section 11 of these Terms of Use is important because MATIXdental - as an e-commerce platform - disclaims certain warranties and liabilities. You understand this agreement means MATIXdental will not assume responsibility for many items.</p>
                    <p>THIS DISCLAIMER SECTION IS AN ESSENTIAL PART OF THIS AGREEMENT. THIS DISCLAIMER DOES NOT APPLY TO ANY PRODUCT WARRANTY MADE TO YOU BY THE MANUFACTURER OF THE ITEM. </p>
                    <p>MATIXDENTAL, AND ALL INFORMATION, CONTENT, MATERIALS, PRODUCTS, ADVICE, AND OTHER SERVICES INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH MATIXDENTAL ARE PROVIDED SOLELY ON AN 'AS IS' AND 'AS AVAILABLE' BASIS, AND THEREFORE YOUR USE OF MATIXDENTAL IS AT YOUR RISK.</p>
                    <p>WE DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED. THESE DISCLAIMERS INCLUDE, WITHOUT LIMITATION:</p>
                    <ul>
                        <li>THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE;</li>
                        <li>ANY WARRANTIES IMPLIED FROM A COURSE OF PERFORMANCE OR COURSE OF DEALING;</li>
                        <li>THAT ACCESS TO MATIXDENTAL WILL BE UNINTERRUPTED OR ERROR-FREE;</li>
                        <li>THAT MATIXDENTAL WILL BE SECURE;</li>
                        <li>THAT MATIXDENTAL OR THE SERVERS THAT MAKE MATIXDENTAL AVAILABLE WILL BE VIRUS-FREE; AND</li>
                        <li>THAT COMMUNICATIONS SENT FROM MATIXDENTAL ARE FREE OF MALWARE OR OTHER HARMFUL COMPONENTS.</li>
                    </ul>
                    <p>YOU ACKNOWLEDGE AND AGREE THAT YOU ASSUME FULL RESPONSIBILITY FOR YOUR USE OF MATIXDENTAL AND THAT ANY INFORMATION YOU SEND OR RECEIVE DURING YOUR USE OF MATIXDENTAL MAY NOT BE SECURE AND MAY BE INTERCEPTED OR OTHERWISE ACCESSED BY UNAUTHORIZED PARTIES. YOU AGREE THAT MATIXDENTAL IS NOT RESPONSIBLE FOR ANY LOSS OR DAMAGE TO YOUR PROPERTY OR DATA THAT RESULTS FROM ANY MATERIALS YOU ACCESS OR DOWNLOAD FROM MATIXDENTAL.</p>
                    <p>CERTAIN STATE LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU DESPITE THE &ldquo;NEW&nbsp;YORK LAW APPLIES&rdquo; SECTION OF THESE TERMS OF USE (SEE SECTION 14), SOME OR ALL OF THE ABOVE MAY NOT APPLY TO YOU, AND YOU MIGHT HAVE ADDITIONAL RIGHTS.</p>
                    <h4><strong>12. LIMITATION OF LIABILITY</strong></h4>
                    <p>This section 12 of these Terms of Use is also important because MATIXdental limits many of its liabilities. We must limit our liabilities for many reasons, but mainly because it is smart for us to do so as an e-commerce business that wants to provide our platform to you as efficiently as possible.</p>
                    <p>YOU ACKNOWLEDGE AND AGREE THAT, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, NEITHER MATIXDENTAL, MATIXDENTAL&rsquo;S EMPLOYEES, BOARD OF DIRECTORS, OR INVESTORS, NOR ITS SUPPLIERS OR THIRD PARTY CONTENT PROVIDERS WILL BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, EXEMPLARY, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR, OTHER DAMAGES ARISING OUT OF OR IN ANY WAY RELATED TO:</p>
                    <ul>
                        <li>MATIXDENTAL, OR ANY OTHER SITES YOU ACCESS THROUGH A LINK FROM MATIXDENTAL;</li>
                        <li>ANY ACTIONS WE TAKE OR FAIL TO TAKE AS A RESULT OF COMMUNICATIONS YOU SEND TO US;</li>
                        <li>ANY DELAY ON OR INABILITY TO USE MATIXDENTAL OR ANY INFORMATION, PRODUCTS, OR SERVICES ADVERTISED ON OR OBTAINED THROUGH MATIXDENTAL;</li>
                        <li>MATIXDENTAL&rsquo;S REMOVAL OR DELETION OF ANY MATERIALS SUBMITTED OR POSTED ON MATIXDENTAL, OR;</li>
                        <li>OTHERWISE ARISING OUT OF YOUR USE OF MATIXDENTAL;</li>
                    </ul>
                    <p>IN EACH CASE, WHETHER BASED ON CONTRACT, TORT, STRICT LIABILITY, OR OTHERWISE, EVEN IF MATIXDENTAL, ITS SUPPLIERS OR THIRD PARTY CONTENT PROVIDERS, OR ANY OTHER PERSON HAS BEEN ADVISED OF THE POSSIBILITY OF DAMAGES.</p>
                    <p>THIS DISCLAIMER APPLIES, WITHOUT LIMITATION, TO ANY DAMAGES OR INJURY ARISING FROM ANY FAILURE OF PERFORMANCE, ERROR, OMISSION, INTERRUPTION, DELETION, DEFECTS, DELAY IN OPERATION OR TRANSMISSION, COMPUTER VIRUSES, FILE CORRUPTION, COMMUNICATION-LINE FAILURE, NETWORK OR SYSTEM OUTAGE, YOUR LOSS OF PROFITS, ANY THEFT, DESTRUCTION, UNAUTHORIZED ACCESS TO, ALTERATION OF, LOSS OR USE OF, ANY RECORD OR DATA, AND ANY OTHER TANGIBLE OR INTANGIBLE LOSS.</p>
                    <p>YOU SPECIFICALLY ACKNOWLEDGE AND AGREE THAT NEITHER MATIXDENTAL NOR ITS SUPPLIERS SHALL BE LIABLE FOR ANY DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY SELLER, SHOPPER, OR OTHER USER OF MATIXDENTAL.</p>
                    <p>CERTAIN STATE LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU DESPITE THE &ldquo;NEW YORK LAW APPLIES&rdquo; SECTION OF THESE TERMS OF USE (SEE SECTION 14), SOME OR ALL OF THE ABOVE MAY NOT APPLY TO YOU, AND YOU MIGHT HAVE ADDITIONAL RIGHTS.</p>
                    <h4><strong>13. Indemnification</strong></h4>
                    <p>You agree to indemnify, defend, and hold harmless MATIXdental and its subsidiaries and affiliates, and as to each, their officers, directors, employees, contractors, agents, licensors, service or third party providers, subcontractors, and suppliers, from and against any and all losses, liabilities, expenses, damages, and costs, including reasonable attorneys&rsquo; fees and court costs, arising out of or relating to your access to or use of MATIXdental, any content you post or submit to MATIXdental, your violation of law or infringement of the rights of a third party, or your other violation of these Terms of Use. MATIXdental reserves the right, at its own expense, to assume exclusive defense and control of any matter otherwise subject to indemnification by you and, in any case, you agree to cooperate with MATIXdental if and as requested by MATIXdental in the defense of such matter.</p>
                    <h4><strong>14. New York Law Applies</strong></h4>
                    <p>The laws of the State of New York apply to everything relating to MATIXdental&rsquo;s and MATIXdental&rsquo; relationship to you. This means that any and all disputes, claims and controversies arising out of or relating to MATIXdental, including the sale of products, content, services, or technology, on or used through MATIXdental, shall be governed by and construed exclusively in accordance with the laws and decisions of the State of New York applicable to contracts made, entered into and performed entirely therein, without giving effect to its conflict of laws provisions (except for Sections 5-1401 and 5-1402 of the New York General Obligations Law). The United Nations Convention on Contracts for the International Sale of Goods shall not apply.</p>
                    <h4><strong>15. Disputes/Arbitration</strong></h4>
                    <p>PLEASE READ THIS SECTION CAREFULLY. IT MAY SIGNIFICANTLY AFFECT YOUR LEGAL RIGHTS, INCLUDING YOUR RIGHT TO FILE A LAWSUIT IN COURT. MATIXdental and you agree that these Terms of Use affect interstate commerce and that the Federal Arbitration Act governs the interpretation and enforcement of the provisions in this section 15.</p>
                    <p>For purposes of this section 15, we will use the capitalized word &ldquo;Dispute&rdquo; to mean any dispute, claim, or controversy arising out of or relating to these Terms of Use (such as with respect to their validity or enforceability), MATIXdental, your (or anybody else&rsquo;s) access to and/or use of MATIXdental, and/or the provision of content, products, services, and/or technology on or through MATIXdental.</p>
                    <p>In the event of a Dispute, MATIXdental or you must give the other notice of the Dispute. This notice must include a brief written statement that sets forth the name, address, and contact information of the party giving it, as well as the facts giving rise to the Dispute and the relief requested. You must send any such notice to MATIXdental by email to legal@MATIXdental.com and by U.S. Mail to MATIXdental.com, Inc., Legal Notice, to: 700 S Flower Street Suite 2990, Los Angeles, CA 90017. To the extent that MATIXdental has your contact information, it will send any such notice to you by U.S. Mail and your email address.</p>
                    <p>We will try to resolve any Dispute through informal negotiation within 30 days from the date that any notice of Dispute is sent by email and U.S. Mail. MATIXdental and you shall use reasonable, good faith efforts to settle any Dispute through consultation and good faith negotiations. After 30 days, MATIXdental or you may resort to the other alternatives described in this section.</p>
                    <p>Notwithstanding the foregoing, Disputes concerning patents, copyrights, moral rights, trademarks, and trade secrets and claims of piracy or unauthorized use of MATIXdental shall not be subject to arbitration, and the notice and 30-day negotiation period required by this paragraph shall not apply to these types of Disputes.</p>
                    <p>Except as otherwise specifically set forth below, any Dispute of any kind, if unresolved through informal discussions within 30 days of the sending of the notice described above, shall be resolved by binding arbitration to be held in the U.S. state in which you reside. For residents outside the United States, arbitration shall be initiated in New York, New York, and MATIXdental and you agree to submit to the personal jurisdiction of any state or federal court in New York, New York to compel arbitration, stay proceedings pending arbitration, or to confirm, modify, vacate, or enter judgment on the award entered by the arbitrator.</p>
                    <p>The arbitration shall be conducted by a single arbitrator, governed by the Commercial Arbitration Rules and the Supplementary Procedures for Consumer Related Disputes (collectively, &ldquo;AAA Rules&rdquo;) of the American Arbitration Association (&ldquo;AAA&rdquo;), as modified by these Terms of Use, and administered by the AAA. The AAA Rules and fee information are available at <a href="http://www.adr.org/">www.adr.org</a> or by calling the AAA at 1 (800) 778-7879.</p>
                    <p>You are responsible for all costs that you may incur in the arbitration including, without limitation, filing fees, attorney&rsquo;s fees and expert witness costs unless MATIXdental is specifically required to pay such fees under applicable law. For claims that total more than $75,000, the AAA Rules will govern payment of filing fees and arbitration fees. The decision of the arbitrator will be in writing and binding and conclusive on MATIXdental and you, and judgment to enforce the decision may be entered by any court of competent jurisdiction. MATIXdental and you agree that dispositive motions, including without limitation motions to dismiss and motions for summary judgment, will be allowed in the arbitration. The arbitrator must follow these Terms of Use and can award the same damages and relief as a court, including injunctive or other equitable relief and attorney&rsquo;s fees. MATIXdental and you understand that, absent this mandatory arbitration provision, MATIXdental and you would have the right to sue in court and have a jury trial. MATIXdental and you further understand that, in some instances, the costs of arbitration could exceed the costs of litigation and that the right to discovery may be more limited in arbitration than in court.</p>
                    <p>If MATIXdental&rsquo;s or your claim is solely for monetary relief of $10,000 or less and does not include a request for any type of equitable remedy, the party bringing the claim may choose whether the arbitration of the claim will be conducted, through a telephonic hearing, or by an in-person hearing under the AAA Rules, solely based on documents submitted to the arbitrator.</p>
                    <p>You or MATIXdental may choose to pursue a claim in small claims court where jurisdiction and venue over you and MATIXdental otherwise qualifies for such small claims court and where the claim does not include a request for any type of equitable relief. However, if you decide to pursue a claim in small claims court, you agree to still provide MATIXdental 30-day advance notice by email to legal@MATIXdental.com and by U.S. Mail to MATIXdental.com, Inc., Legal Notice, to: 700 S Flower Street Los Angeles Suite 2990, CA 90017.</p>
                    <p>You have the right to opt out and not be bound by the provisions requiring arbitration by sending written notice of your decision to opt out to MATIXdental by email to legal@MATIXdental.com AND by U.S. Mail to dentomatix.com,LLC 700 S Flower Street Los Angeles Suite 2990, CA 90017. The notice must be sent within 30 days of your first use of MATIXdental. If you do not opt out via this method, you will be bound to arbitrate Disputes in accordance with the terms of these paragraphs. If you opt out of the provisions requiring arbitration, MATIXdental will not be bound by them either. If any clause within this Disputes/Arbitration section is found to be illegal or unenforceable, that specific clause will be severed from this section, and the remainder of its provisions will be given full force and effect. In any event, if for any reason a Dispute between MATIXdental and you is before a court (e.g., if the arbitration provisions are found unenforceable or if pursuant to these Terms of Use the matter is not subject to arbitration), MATIXdental and you agree to waive, to the fullest extent allowed by law, any trial by jury.</p>
                    <p>This Disputes/Arbitration section will also apply to any claims asserted by you against any present or future parent, subsidiary, or affiliated company of MATIXdental, or any employee, officer, director, or investor of MATIXdental, and to any claims asserted by any of them against you, to the extent that any such claims arise out of or relate to these Terms of Use (such as with respect to their validity or enforceability), MATIXdental, any person&rsquo;s access to and/or use of MATIXdental, and/or the provision of content, products, services, and/or technology on or through MATIXdental.</p>
                    <h4><strong>16. Class Action Waiver</strong></h4>
                    <p>PLEASE READ THIS SECTION CAREFULLY. IT MAY SIGNIFICANTLY AFFECT YOUR LEGAL RIGHTS.</p>
                    <p>For purposes of this section 16, we will also use the capitalized word &ldquo;Dispute&rdquo; to mean any dispute, claim, or controversy arising out of or relating to these Terms of Use (such as with respect to their validity or enforceability), MATIXdental, your (or anybody else&rsquo;s) access to and/or use of MATIXdental, and/or the provision of content, products, services, and/or technology on or through MATIXdental. MATIXdental and you agree to resolve any Dispute will be brought in an individual capacity, and not on behalf of, or as part of, any purported class, consolidated, or representative proceeding. MATIXdental and you further agree to not participate in any consolidated, class, or representative proceeding (existing or future) brought by any third party arising out of or relating to any Dispute with a third party.</p>
                    <p>If any court or arbitrator determines that the class/consolidated/representative action waiver set forth in this section is void or unenforceable for any reason or that arbitration can proceed on a class, consolidated, or representative basis, then the disputes, claims, or controversies will not be subject to arbitration and must be litigated in federal court located in New York County, New York.</p>
                    <p>If any clause within this Class Action Waiver section is found to be illegal or unenforceable, that specific clause will be severed from this section, and the remainder of its provisions will be given full force and effect.</p>
                    <p>This Class Action Waiver section will also apply to any claims asserted by you against any present or future parent, subsidiary or affiliated company of MATIXdental, or any employee, officer, director, or investor of MATIXdental, and to any claims asserted by any of them against you, to the extent that any such claims is a Dispute.</p>
                    <h4><strong>17. Changes to These Terms of Use</strong></h4>
                    <p>MATIXdental may amend these Terms of Use (including any Service Terms) at any time and at MATIXdental&rsquo;s sole discretion by posting the updated version on <a href="http://www.jet.com/">www.MATIXdental.com</a>:</p>
                    <ul>
                        <li>12:00 p.m. Eastern time on the 10th day after posting to <a href="http://www.jet.com/">www.MATIXdental.com</a> (if there is no material update to the Disputes/Arbitration section) or on the 30th day after posting (if there is a material update to the Disputes/Arbitration section); or</li>
                        <li>your acceptance of them via a click-through process or some other method that we specify.</li>
                    </ul>
                    <p>Updates to the Terms of Use apply on a going-forward basis as of the date they take effect.</p>
                    <h4><strong>18. Termination by MATIXdental</strong></h4>
                    <p>We may close your account at any time in our sole discretion and without notice to you. While we always want to promote a great shopping experience at MATIXdental, this means we can close (or suspend) your account if we believe you are using MATIXdental in a manner not intended by us, or in a way that circumvents these Terms of Use, or is contrary to the spirit of any activity on MATIXdental (like a promotion or contest). In no case will MATIXdental&rsquo;s closure of your account, or reduction of your access to MATIXdental, waive or affect any other right or relief to which MATIXdental may be entitled.</p>
                    <h4><strong>19. Additional Terms For Our iOS App</strong></h4>
                    <p>When you use our iOS App, Apple requires you to agree to the following additional terms:</p>
                    <p>You acknowledge and agree that (i) these Terms of Use are concluded between you and MATIXdental only, and Apple is not a party hereto, and (ii) as between MATIXdental and Apple, it is MATIXdental that is responsible for the app and the content thereof. You must use the iOS app only on an Apple-branded product that runs iOS. Your use of the app must comply with the terms of use applicable to the Apple source from which you obtain it (including the Usage Rules set forth in the Apple App Store Terms of Service). You acknowledge that Apple has no obligation to furnish you with any maintenance and support services with respect to the app.</p>
                    <p>You acknowledge that Apple is not responsible for addressing any claims you have or any claims of any third party relating to the app or your possession and use of the app, including, but not limited to (i) product warranty or liability claims; (ii) any claim that the app fails to conform to any applicable legal or regulatory requirement; (iii) claims arising under consumer protection or similar legislation; or (iv) claims that the app infringes a third party&rsquo;s intellectual property rights.</p>
                    <p>In the event of any failure of the iOS version of the app to conform to any applicable warranty that has not been effectively disclaimed by these Terms of Use, you may notify Apple, and Apple will refund the purchase price for the app (if any) to you; to the maximum extent permitted by applicable law, Apple will have no other warranty obligation whatsoever with respect to the app, and, as between Apple and MATIXdental, any other claims, losses, liabilities, damages, costs, or expenses attributable to any failure to conform to any warranty of MATIXdental will be MATIXdental&rsquo;s responsibility, but only to the extent provided by these Terms of Use. Please read our entire Terms of Use, as other sections of these Terms of Use limit MATIXdental&rsquo;s liability in this regard.</p>
                    <p>Apple, and Apple&rsquo;s subsidiaries, are third-party beneficiaries of these Terms of Use with respect to your compliance with this section. Upon your acceptance of these Terms of Use, Apple will have the right (and will be deemed to have accepted the right) to enforce the Terms of Use against you as a third party beneficiary thereof. There are no other third-party beneficiaries of the Terms.</p>
                    <h4><strong>20. Entire Agreement and Admissibility; Applicability to Sellers</strong></h4>
                    <p>These Terms of Use constitute the entire agreement and understanding between you and MATIXdental with respect to the subject matter hereof and supersede all prior or contemporaneous communications and proposals, whether oral or written, between the parties with respect to such subject matter. A printed version of these Terms of Use shall be admissible in judicial, arbitral, or administrative proceedings to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form.</p>
                    <p>If you access or use MATIXdental in your capacity as a registered MATIXdental retail partner (i.e., a seller who has registered with MATIXdental to sell products on MATIXdental, or a vendor whose own site is powered by a MATIXdental e-commerce engine), then the MATIXdental Retail Partner Agreement will apply to you in connection with such access and use, not these Terms of Use. When a MATIXdental retail partner or other MATIXdental supplier accesses or uses MATIXdental in any other capacity (e.g., as a shopper), these Terms of Use apply and not the MATIXdental Retail Partner Agreement.</p>
                    <h4><strong>21. Miscellaneous</strong></h4>
                    <p>You may not assign or otherwise transfer these Terms of Use, by operation of law or otherwise, without MATIXdental&rsquo;s prior written consent. Subject to the foregoing restriction, these Terms of Use will be binding on, inure to, and enforceable against the parties and their respective successors and assigns. MATIXdental may assign these Terms of Use in its sole discretion by providing you notice of the same. For example, MATIXdental may unconditionally assign or otherwise transfer these Terms of Use to any successor in interest, such as an acquirer of a MATIXdental company (via merger, sale of stock, etc.) or a buyer of substantially all of its assets. Likewise, in the event of a sale or transfer of a user&rsquo;s business, pertinent information may be transferred about that corporation (locations, inventory, etc.) upon written consent to MATIXdental by email to admin@MATIXdental.com and by U.S. Mail to Dentomatix.com, LLC. to: 700 S Flower Street Suite 2990, Los Angeles, CA 90017.</p>
                    <p>Headings are for reference purposes only and do not limit the scope or extent of any section.</p>
                    <p>MATIXdental&rsquo;s failure to enforce your strict performance of any provision of these Terms of Use will not constitute a waiver of MATIXdental&rsquo;s right to enforce such provision or any other provision of these Terms of Use.</p>
                    <p>If any provision of this agreement is unlawful, void or unenforceable, the remaining provisions of the agreement will remain in place, except as explained in the second-to-last paragraphs of the &ldquo;Disputes/Arbitration&rdquo; and &ldquo;Class Action Waiver&rdquo; sections.</p>
                    <h4><strong>22. How to Contact Us</strong></h4>
                    <p>If you have any questions or comments, please contact MATIXdental by:</p>
                    <p>(1) emailing us at admin@MATIXdental.com; </p>
                    <p>(2) Contacting us by phone</p>
                    <p>(3) Mailing us at MATIXdental Help at the following address: 700 S Flower Street Suite 2990 Los Angeles, CA 90017.</p>
                </div>
            </div>
        </div>
    </section>
</div>